### ISSUE TITLE
Hello, i use tensorflow-gpu==2.4.1, keras==2.2.4  ,but have the following error in load_model:

### ISSUE THREAD

**Issue by 191334391** [nacayu/CRFNet_ReproduceOn_Tensorflow2.4.1#6]
Traceback (most recent call last):
  File "data_visualization.py", line 65, in <module>
    model = keras.models.load_model(args.model, custom_objects=backbone.custom_objects)
  File "/home/sunzong/anaconda3/envs/acrfnet04/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/home/sunzong/anaconda3/envs/acrfnet04/lib/python3.6/site-packages/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/sunzong/anaconda3/envs/acrfnet04/lib/python3.6/site-packages/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/sunzong/anaconda3/envs/acrfnet04/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/sunzong/anaconda3/envs/acrfnet04/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/sunzong/anaconda3/envs/acrfnet04/lib/python3.6/site-packages/keras/engine/network.py", line 1022, in from_config
    process_layer(layer_data)
  File "/home/sunzong/anaconda3/envs/acrfnet04/lib/python3.6/site-packages/keras/engine/network.py", line 1008, in process_layer
    custom_objects=custom_objects)
  File "/home/sunzong/anaconda3/envs/acrfnet04/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/sunzong/anaconda3/envs/acrfnet04/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 147, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/home/sunzong/anaconda3/envs/acrfnet04/lib/python3.6/site-packages/keras/engine/base_layer.py", line 1109, in from_config
    return cls(**config)
  File "/home/sunzong/anaconda3/envs/acrfnet04/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/sunzong/anaconda3/envs/acrfnet04/lib/python3.6/site-packages/keras/engine/input_layer.py", line 87, in __init__
    name=self.name)
  File "/home/sunzong/anaconda3/envs/acrfnet04/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 517, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)
AttributeError: module 'tensorflow' has no attribute 'placeholder'

**Comment by nacayu** [comment]
you can following this steps, it might be tf version problem
![image](https://user-images.githubusercontent.com/47105158/217988763-1fa31318-0e11-4b09-88c6-3462576156ab.png)

**Comment by 191334391** [comment]
thank you , I fix this error , but have the  next error:

XXX lineno: 75, opcode: 0
Traceback (most recent call last):
  File "data_visualization.py", line 129, in <module>
    main()
  File "data_visualization.py", line 65, in main
    model = keras.models.load_model(args.model, custom_objects=backbone.custom_objects)
  File "C:\Users\sunheng\.conda\envs\crfnet_new\lib\site-packages\keras\engine\saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "C:\Users\sunheng\.conda\envs\crfnet_new\lib\site-packages\keras\engine\saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Users\sunheng\.conda\envs\crfnet_new\lib\site-packages\keras\engine\saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Users\sunheng\.conda\envs\crfnet_new\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "C:\Users\sunheng\.conda\envs\crfnet_new\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Users\sunheng\.conda\envs\crfnet_new\lib\site-packages\keras\engine\network.py", line 1032, in from_config
    process_node(layer, node_data)
  File "C:\Users\sunheng\.conda\envs\crfnet_new\lib\site-packages\keras\engine\network.py", line 991, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "C:\Users\sunheng\.conda\envs\crfnet_new\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\sunheng\.conda\envs\crfnet_new\lib\site-packages\keras\layers\core.py", line 687, in call
    return self.function(inputs, **arguments)
  File "../ssnn/model/architectures/vggmax.py", line 75, in func
SystemError: unknown opcode

**Comment by nacayu** [comment]
> 

python version error. because your checkpoint is trained based on python3.5, so you should change python version to 3.5 intead of 3.6

**Comment by nacayu** [comment]
> thank you , I fix this error , but have the next error:
> 
> XXX lineno: 75, opcode: 0 Traceback (most recent call last): File "data_visualization.py", line 129, in main() File "data_visualization.py", line 65, in main model = keras.models.load_model(args.model, custom_objects=backbone.custom_objects) File "C:\Users\sunheng.conda\envs\crfnet_new\lib\site-packages\keras\engine\saving.py", line 419, in load_model model = _deserialize_model(f, custom_objects, compile) File "C:\Users\sunheng.conda\envs\crfnet_new\lib\site-packages\keras\engine\saving.py", line 225, in _deserialize_model model = model_from_config(model_config, custom_objects=custom_objects) File "C:\Users\sunheng.conda\envs\crfnet_new\lib\site-packages\keras\engine\saving.py", line 458, in model_from_config return deserialize(config, custom_objects=custom_objects) File "C:\Users\sunheng.conda\envs\crfnet_new\lib\site-packages\keras\layers__init__.py", line 55, in deserialize printable_module_name='layer') File "C:\Users\sunheng.conda\envs\crfnet_new\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object list(custom_objects.items()))) File "C:\Users\sunheng.conda\envs\crfnet_new\lib\site-packages\keras\engine\network.py", line 1032, in from_config process_node(layer, node_data) File "C:\Users\sunheng.conda\envs\crfnet_new\lib\site-packages\keras\engine\network.py", line 991, in process_node layer(unpack_singleton(input_tensors), **kwargs) File "C:\Users\sunheng.conda\envs\crfnet_new\lib\site-packages\keras\engine\base_layer.py", line 457, in **call** output = self.call(inputs, **kwargs) File "C:\Users\sunheng.conda\envs\crfnet_new\lib\site-packages\keras\layers\core.py", line 687, in call return self.function(inputs, **arguments) File "../ssnn/model/architectures/vggmax.py", line 75, in func SystemError: unknown opcode

https://blog.csdn.net/Sarah_LZ/article/details/86526968
this may help you
